# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["test"]
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}", "--build-arg=JAR_FILE=build/libs/hellospring-1.0.0.jar", "."]
  - name: gcr.io/cloud-builders/docker
    args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

  #Update the container image using kubectl set
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

    substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: java-app
    _ZONE: us-central1-a
    _GKE_CLUSTER: java-app
    
    #Repository Specific configuration. DevOps can change this settings
  
    _CONTAINERNAME: hello-world-service    
    
    
    # Developers ONLY change
    _VERSION: v1.0
    
options:
    substitution_option: 'ALLOW_LOOSE'
